# Visualization Research in Biomedical Informatics


## Community Contribution Zoom Session

Adrienne Pichon (ab3886@cumc.columbia.edu) is a 2nd year PhD student in the Department of Biomedical Informatics at Columbia and previously received her MPH in Sociomedical Sciences and Sexuality, Sexual, and Reproductive Health from Columbia's Mailman School of Public Health. Her work focuses on person-generated data and supporting the collaborative work of patients and providers when caring for chronic disease. This zoom session connected visualization principles learned in class to a real-world application.

The hour-long session was held on Friday (11/20 2pm ET) via Zoom 
1. Presentation of recently published paper, eliciting design needs of end-users of an interactive visualization tool (5 min video available)
2. Overview of the Phendo app and aggregate data
3. Discussion of initial tool prototype, for viewing and understanding individual-level data to support care of an enigmatic chronic condition
4. Resources for human-centered computing that were discussed in the zoom session are also listed below

The slides are available [here](../resources/project_pichon/Pichon_CSCW_forEDAVcc_Slides.pdf)


### Designing an Interactive Visualization Tool for Understanding & Caring for a Complex Chronic Condition

Download a [copy of the paper](../resources/project_pichon/Pichon_2020_V4cscw261.pdf), or see current publications: [website](http://www.columbia.edu/~ab3886/) or [google scholar](https://scholar.google.com/citations?user=tWw9g3wAAAAJ&hl=en&oi=ao). 
There is also a [five minute video](https://youtu.be/PtXjzquAjCY) available, that was presented at the CSCW conference. 


In this qualitative research, focus groups with women with endometriosis (a painful chronic illness) and interviewers medical providers who treat the condition provided useful insights on the work of patients and providers in caring for this enigmatic condition. 
Findings from thematic analysis enabled identification of 3 design opportunities. 
The talk highlighted the potential applications of visualization techniques and innovation that we plan to incorporate into the design of this tool. 


### Phendo App & Prototype of Interactive Visualization
A high-level view of the phendo app and data for users was presented. 

Finally, we reviewed an early prototype of the interactive visualization tool. This early version uses D3 to display a heatmap of self-tracked symptom data in a unified timeline. Discussing and brainstorming this early prototype together with peers made it possible to integrate principles from the EDAV class to this real-world application. 



### Resources for Human-Centered Visualization & Computing


*Data Feminism*

D’Ignazio, C., & Klein, L. F. (2020). Data Feminism. MIT Press.

- open access, free online; also webinar recordings and sketchnotes from sessions with the authors: [http://datafeminism.io/]

*Race After Technology*

Benjamin, R. (2019). Race After Technology: Abolitionist Tools for the New Jim Code. John Wiley & Sons.
- [https://www.ruhabenjamin.com/race-after-technology]

*Design Justice*
Costanza-Chock, S. (2018). Design Justice: Towards an Intersectional Feminist Framework for Design Theory and Practice (SSRN Scholarly Paper ID 3189696). Social Science Research Network. 
- [https://designjustice.org/]


*Data Comics*

Bach, B., Wang, Z., Farinella, M., Murray-Rust, D., & Henry Riche, N. (2018). Design Patterns for Data Comics. Proceedings of the 2018 CHI Conference on Human Factors in Computing Systems, 38:1–38:12. [https://doi.org/10.1145/3173574.3173612]

Bach, B., Riche, N. H., Carpendale, S., & Pfister, H. (2017). The Emerging Genre of Data Comics. IEEE Computer Graphics and Applications, 37(3), 6–13. [https://doi.org/10.1109/MCG.2017.33]





